name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Productive Gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9db17f016174a768dbaa16454ba295c0
          TIMEZONE: Asia/Shanghai

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0

      - name: Update
        run: npx -y github-lang-box 
        env:
          GH_USERNAME: ${{ github.actor }}
          GIST_ID: bf4c3cf669ab7930d2979b3d8b45d694
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

