name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Productive Gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9db17f016174a768dbaa16454ba295c0
          TIMEZONE: Asia/Shanghai

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Update
        run: pnpm dlx github-lang-box@2
        env:
          GH_USERNAME: your-username
          GIST_ID: bf4c3cf669ab7930d2979b3d8b45d694
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

